### ISSUE TITLE
Unable to compile on Linux (Centos 7)

### ISSUE THREAD

**Issue by lenck** [abarbu/ffmpeg-matlab#1]
Hi, I was unable to compile on Centos 7, Matlab R2016a. Had to change the Makefile to:

```
mex -v CC=gcc CFLAGS='$$CFLAGS -Wall -std=c99' ffmpeg-matlab.c -Output ffmpeg $(FFMPEG_LDFLAGS)
```

**Comment by abarbu** [comment]
mex has changed over the years it seems. I updated the makefile. There's also an update for newer ffmpeg versions. Feel free to reopen if you encounter more troubles.
